name = "spr-heartbeat-publisher"
main = "src/index.js"
compatibility_date = "2026-10-02"
workers_dev = true

[vars]
UPDATER_STATUS_URL = "https://www.bodgybros.com/sps/updater-status.json"
MAX_AGE_SECONDS = "7200"

[triggers]
crons = ["0 * * * *"]

[[kv_namespaces]]
binding = "SPR_COMMANDS"
id = "389b0466caae47979a1cdbda5985aa24"
